### ISSUE TITLE
Error after compilation

### ISSUE THREAD

**Issue by yegya** [stephenmathieson/node-obfuscator#22]
Thank you for this great script. It does the job very nice, changed my variable contents to hex code and I kinda like it, only to give error when I tried to run my script.

After the successful compilation, when I use my compiled script on the browser, it give me lots of unexpected errors like ". (" etc.
Isn't there any way to get rid of those errors. It is useless if I get unexpected errors in my script with the compiled script. So for now I've switched back to uglify plugin of grunt.

Any suggestions???

N.B. I was using my client side script to obfuscate, and its a huge chunk of file, more than 300kb without minification.

**Comment by stephenmathieson** [comment]
I haven't run browser code through obfuscator, but it *should* work.

Syntax errors aren't good.  Can you show me the compiled script?

**Comment by stephenmathieson** [comment]
closing as inactive.. feel free to reopen if you'd like to try to work this out
