### ISSUE TITLE
TypeError: Cannot set property '.jse' of undefined

### ISSUE THREAD

**Issue by manuks** [stephenmathieson/node-obfuscator#23]
Hi,

I was trying to obfuscate a code with
```javascript
    require.extensions['.jse] = function(module, filename) {
        var content = fs.readFileSync(filename, 'utf8');
        return module._compile(content, filename);
    };
```
But got the following error when the output file is executed 
TypeError: Cannot set property '.jse' of undefined

How to fix this? Any clue?

**Comment by stephenmathieson** [comment]
node [deprecated `require.extensions`](https://nodejs.org/api/globals.html#globals_require_extensions) a long time ago.  i've documented the fact that [it doesn't work with obfuscator](https://github.com/stephenmathieson/node-obfuscator#known-bugs-and-limitations), and have no intentions of adding support for it.

closing as "will not fix".
